spring:
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    username: liulangsha
    password: liu123
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      maximum-pool-size: 10

  # MyBatis Configuration
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.southern.dataconsistencychecker.entity
  configuration:
#     开启驼峰命名
    map-underscore-to-camel-case: true

# 其他配置
logging:
  level:
    root: INFO
    com:
      southern:
        dataconsistencychecker: DEBUG